language: rust

cache: cargo

addons:
  apt:
    packages:
      - libssl-dev

matrix:
  include:
    - env: GEO_FEATURES="" GEO_TYPES_FEATURES="" RUN_TARPAULIN=1
    - env: GEO_FEATURES="--features use-proj"
    - env: GEO_FEATURES="--features postgis-integration"
    - env: GEO_FEATURES="--features use-serde"
    - env: GEO_TYPES_FEATURES="--features serde"
    - env: GEO_TYPES_FEATURES="--features rstar"

before_install:
  - if [ "${GEO_FEATURES}" == "--features use-proj" ]; then
        sudo apt-get update;
        wget https://github.com/OSGeo/PROJ/releases/download/7.0.0/proj-7.0.0.tar.gz;
        tar -xzvf proj-7.0.0.tar.gz;
        pushd proj-7.0.0 && ./configure --prefix=/usr && make && sudo make install && popd;
    fi
  - if [[ "${TRAVIS_RUST_VERSION}" == stable && "${RUN_TARPAULIN}" ]]; then
      cargo install cargo-tarpaulin;
    fi

script:
  - (cd geo-types && cargo build --release $GEO_TYPES_FEATURES && cargo test --release $GEO_TYPES_FEATURES)
  - (cd geo && cargo build --release $GEO_FEATURES && cargo test --release $GEO_FEATURES)

after_success:
  - if [[ "${TRAVIS_RUST_VERSION}" == stable && "${RUN_TARPAULIN}" ]]; then
      cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID;
    fi
